<?php

use App\Models\Airport;
use Illuminate\Database\Seeder;

class AirportsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $airports = [
            ['code' => 'ESB', 'name' => 'Esenboga Arpt'],
            ['code' => 'AJI', 'name' => 'Agri Airport'],
            ['code' => 'AFY', 'name' => 'Afyon Arpt'],
            ['code' => 'ADF', 'name' => 'Adiyaman Airport'],
            ['code' => 'ADA', 'name' => 'Adana Arpt'],
            ['code' => 'AOE', 'name' => 'Anadolu University Airport'],
            ['code' => 'ASR', 'name' => 'Kayseri Arpt'],
            ['code' => 'AYT', 'name' => 'Antalya Airport'],
            ['code' => 'BAL', 'name' => 'Batman Arpt'],
            ['code' => 'BDM', 'name' => 'Bandirma Arpt'],
            ['code' => 'YEI', 'name' => 'Yenisehir Arpt'],
            ['code' => 'BTZ', 'name' => 'Bursa Arpt'],
            ['code' => 'BJV', 'name' => 'Milas Arpt'],
            ['code' => 'BZI', 'name' => 'Balikesir'],
            ['code' => 'MQJ', 'name' => 'Merkez Arpt'],
            ['code' => 'CKZ', 'name' => 'Canakkale Arpt'],
            ['code' => 'DIY', 'name' => 'Diyarbakir Arpt'],
            ['code' => 'DLM', 'name' => 'Dalaman Airport'],
            ['code' => 'DNZ', 'name' => 'Cardak Arpt'],
            ['code' => 'EDO', 'name' => 'Edremit Airport'],
            ['code' => 'ERC', 'name' => 'Erzincan Arpt'],
            ['code' => 'ERZ', 'name' => 'Erzurum Arpt'],
            ['code' => 'ESK', 'name' => 'Eskisehir Airport'],
            ['code' => 'EZS', 'name' => 'Elazig Arpt'],
            ['code' => 'GKD', 'name' => 'GOKCEADA'],
            ['code' => 'GZP', 'name' => 'Gazipasa Arpt'],
            ['code' => 'GZT', 'name' => 'Gaziantep Arpt'],
            ['code' => 'HTY', 'name' => 'Hatay Airport'],
            ['code' => 'IGD', 'name' => 'Iğdır Havalimanı'],
            ['code' => 'ISE', 'name' => 'Isparta Suleyman Demirel Airport'],
            ['code' => 'IST', 'name' => 'Ataturk Arpt'],
            ['code' => 'SAW', 'name' => 'Sabiha Gokcen Arpt'],
            ['code' => 'ADB', 'name' => 'Adnan Menderes Airport'],
            ['code' => 'KCM', 'name' => 'Kahramanmaras aRPT'],
            ['code' => 'KCO', 'name' => 'Kocaeli'],
            ['code' => 'KFS', 'name' => 'Kastamonu Arpt'],
            ['code' => 'KSY', 'name' => 'Kars Arpt'],
            ['code' => 'KYA', 'name' => 'Konya Arpt'],
            ['code' => 'KZR', 'name' => 'Zafer Arpt'],
            ['code' => 'MLX', 'name' => 'Malatya Arpt'],
            ['code' => 'MQM', 'name' => 'Mardin Arpt'],
            ['code' => 'MSR', 'name' => 'Mus Arpt'],
            ['code' => 'MZH', 'name' => 'Merzifon Airport'],
            ['code' => 'NAV', 'name' => 'Nevsehir Arpt'],
            ['code' => 'ONQ', 'name' => 'Zonguldak Airport'],
            ['code' => 'SFQ', 'name' => 'Sanli Urfa Arpt'],
            ['code' => 'GNY', 'name' => 'Guney Anadolu Airport'],
            ['code' => 'NOP', 'name' => 'Sinop Arpt'],
            ['code' => 'SZF', 'name' => 'Carsamba Arpt'],
            ['code' => 'SXZ', 'name' => 'Siirt Airport'],
            ['code' => 'TEQ', 'name' => 'Corlu Airport Information'],
            ['code' => 'TJK', 'name' => 'TOKAT HAVALIMANI'],
            ['code' => 'TZX', 'name' => 'Trabzon Arpt'],
            ['code' => 'USQ', 'name' => 'Usak Airport'],
            ['code' => 'VAN', 'name' => 'Van Arpt'],
            ['code' => 'VAS', 'name' => 'Sivas Arpt'],
            ['code' => 'XHQ', 'name' => 'Hopa Artvin'],
            ['code' => 'ADA', 'name' => 'Adana Arpt'],
            ['code' => 'ADF', 'name' => 'Adiyaman Airport'],
            ['code' => 'AFY', 'name' => 'Afyon Arpt'],
            ['code' => 'AJI', 'name' => 'Agri Airport'],
            ['code' => 'ESB', 'name' => 'Esenboga Arpt'],
            ['code' => 'AOE', 'name' => 'Anadolu University Airport'],
            ['code' => 'ASR', 'name' => 'Kayseri Arpt'],
            ['code' => 'AYT', 'name' => 'Antalya Airport'],
            ['code' => 'BAL', 'name' => 'Batman Arpt'],
            ['code' => 'BDM', 'name' => 'Bandirma Arpt'],
            ['code' => 'YEI', 'name' => 'Yenisehir Arpt'],
            ['code' => 'BTZ', 'name' => 'Bursa Arpt'],
            ['code' => 'BJV', 'name' => 'Milas Arpt'],
            ['code' => 'BZI', 'name' => 'Balikesir'],
            ['code' => 'MQJ', 'name' => 'Merkez Arpt'],
            ['code' => 'CKZ', 'name' => 'Canakkale Arpt'],
            ['code' => 'DIY', 'name' => 'Diyarbakir Arpt'],
            ['code' => 'DLM', 'name' => 'Dalaman Airport'],
            ['code' => 'DNZ', 'name' => 'Cardak Arpt'],
            ['code' => 'EDO', 'name' => 'Edremit Airport'],
            ['code' => 'ERC', 'name' => 'Erzincan Arpt'],
            ['code' => 'ERZ', 'name' => 'Erzurum Arpt'],
            ['code' => 'ESK', 'name' => 'Eskisehir Airport'],
            ['code' => 'EZS', 'name' => 'Elazig Arpt'],
            ['code' => 'GKD', 'name' => 'GOKCEADA'],
            ['code' => 'GZP', 'name' => 'Gazipasa Arpt'],
            ['code' => 'GZT', 'name' => 'Gaziantep Arpt'],
            ['code' => 'HTY', 'name' => 'Hatay Airport'],
            ['code' => 'IGD', 'name' => 'Iğdır Havalimanı'],
            ['code' => 'ISE', 'name' => 'Isparta Suleyman Demirel Airport'],
            ['code' => 'IST', 'name' => 'Ataturk Arpt'],
            ['code' => 'SAW', 'name' => 'Sabiha Gokcen Arpt'],
            ['code' => 'ADB', 'name' => 'Adnan Menderes Airport'],
            ['code' => 'KCM', 'name' => 'Kahramanmaras aRPT'],
            ['code' => 'KCO', 'name' => 'Kocaeli'],
            ['code' => 'KFS', 'name' => 'Kastamonu Arpt'],
            ['code' => 'KSY', 'name' => 'Kars Arpt'],
            ['code' => 'KYA', 'name' => 'Konya Arpt'],
            ['code' => 'KZR', 'name' => 'Zafer Arpt'],
            ['code' => 'MLX', 'name' => 'Malatya Arpt'],
            ['code' => 'MQM', 'name' => 'Mardin Arpt'],
            ['code' => 'MSR', 'name' => 'Mus Arpt'],
            ['code' => 'MZH', 'name' => 'Merzifon Airport'],
            ['code' => 'NAV', 'name' => 'Nevsehir Arpt'],
            ['code' => 'ONQ', 'name' => 'Zonguldak Airport'],
            ['code' => 'SFQ', 'name' => 'Sanli Urfa Arpt'],
            ['code' => 'GNY', 'name' => 'Guney Anadolu Airport'],
            ['code' => 'NOP', 'name' => 'Sinop Arpt'],
            ['code' => 'SZF', 'name' => 'Carsamba Arpt'],
            ['code' => 'SXZ', 'name' => 'Siirt Airport'],
            ['code' => 'TEQ', 'name' => 'Corlu Airport Information'],
            ['code' => 'TJK', 'name' => 'TOKAT HAVALIMANI'],
            ['code' => 'TZX', 'name' => 'Trabzon Arpt'],
            ['code' => 'USQ', 'name' => 'Usak Airport'],
            ['code' => 'VAN', 'name' => 'Van Arpt'],
            ['code' => 'VAS', 'name' => 'Sivas Arpt'],
            ['code' => 'XHQ', 'name' => 'Hopa Artvin']
        ];

        foreach ($airports as $name) {
            Airport::create(
                $name
            );
        }
    }
}
