<?php

use App\Models\Facility\Facility;
use Illuminate\Database\Seeder;

class FacilitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $facilities = [
            [ 'facility_category_id' => 6 , 'name' => ' Otopark Hizmeti', 'icon' => '7-emin-otopark-otomasyon.png'],
            [ 'facility_category_id' => 1 , 'name' => 'Deniz Bisikleti', 'icon' => 'denizbisikleti.png'],
            [ 'facility_category_id' => 1 , 'name' => 'Deniz Bisikleti', 'icon' => 'denizbisikleti1.png'],
            [ 'facility_category_id' => 2 , 'name' => ' Bayanlar Mescidi', 'icon' => 'mescid.png'],
            [ 'facility_category_id' => 2 , 'name' => ' Baylar Mescidi', 'icon' => 'mescid1.png'],
            [ 'facility_category_id' => 2 , 'name' => ' Kuran-ı Kerim', 'icon' => 'kur-an-i-kerim.png'],
            [ 'facility_category_id' => 2 , 'name' => ' Seccade', 'icon' => 'seccade.png'],
            [ 'facility_category_id' => 2 , 'name' => ' Tesbih', 'icon' => 'tesbih.png'],
            [ 'facility_category_id' => 2 , 'name' => ' Sohbet Odaları', 'icon' => 'sohbetodalari.png'],
            [ 'facility_category_id' => 3 , 'name' => ' Toprak', 'icon' => 'toprak.png'],
            [ 'facility_category_id' => 5 , 'name' => ' Aqua Park', 'icon' => 'aquapark.png'],
            [ 'facility_category_id' => 8 , 'name' => ' Amfi Tiyatro', 'icon' => 'amfitiyatro.png'],
            [ 'facility_category_id' => 10 , 'name' => ' Uydu Kanalları', 'icon' => 'uydukanallari.png'],
            [ 'facility_category_id' => 9 , 'name' => ' Lokanta Alakart', 'icon' => 'lokantaalakart.png'],
            [ 'facility_category_id' => 9 , 'name' => ' Reseption 7/24', 'icon' => 'icon-7-24.png'],
            [ 'facility_category_id' => 6 , 'name' => ' 24 Saat Açık Resepsiyon', 'icon' => '724resepsion.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Aile Odaları', 'icon' => 'aileodalari.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Anti-Alerjik Oda', 'icon' => 'antidezenfekte.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Asansör', 'icon' => 'asansor.png'],
            [ 'facility_category_id' => 6 , 'name' => 'Bagaj Muhafavazası', 'icon' => 'baagajmuhavazasi.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Bahçe', 'icon' => 'bahce.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Bar', 'icon' => 'bar.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Barber-Beauty Shop', 'icon' => 'barber-beautyshop.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Bisiklet ve Motosiklet İçin P', 'icon' => 'bisikletpark.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Tüm Genel ve Özel Alanlarda S', 'icon' => 'sigaraicemekyasak.png'],
            [ 'facility_category_id' => 6 , 'name' => 'Asansör', 'icon' => 'asansor1.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Denize Sıfır', 'icon' => 'denizesifir.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Disco (Kışlık)', 'icon' => 'disco.png'],
            [ 'facility_category_id' => 6 , 'name' => 'Disco (Yazlık)', 'icon' => 'disco1.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Dizayn Otel', 'icon' => 'dizaynotel.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Duman Alarmı', 'icon' => 'dumanalarmi.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Emanet Kasası', 'icon' => 'emanetkasasi.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Engelli Konuklar İçin Odalar', 'icon' => 'engellikonuklaricinoda.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Evcil Hayvan Kabul Edilemez', 'icon' => 'evcilhayvankabuledilemez.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Garaj', 'icon' => 'garaj.png'],
            [ 'facility_category_id' => 1 , 'name' => ' Gazate', 'icon' => 'gazete.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Güneş Terası', 'icon' => 'günesterasi.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Halı Kaplı Odalar', 'icon' => 'halikapli.png'],
            [ 'facility_category_id' => 5 , 'name' => 'Hızlı Check in Check out', 'icon' => 'hızlichankinchakout.png'],
            [ 'facility_category_id' => 6 , 'name' => 'Hızlı Check in Check out', 'icon' => 'hızlichankinchakout1.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Isıtma', 'icon' => 'isitma.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Kahve Büfesi', 'icon' => 'kahvebufesi.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Kayak Ekipmanı Temini', 'icon' => 'kayakekipmani.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Klima', 'icon' => 'kilma.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Lobi Bar', 'icon' => 'lobibar.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Mağzalar', 'icon' => 'magazalar.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Otelde Mağzalar', 'icon' => 'otelde_magazalar.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Otelin Kendi Park Alanı Mevcu', 'icon' => 'otelinkendiparkalanimevcut.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Otel Plaj Alanı', 'icon' => 'otelplajalani.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Özel Sigara İçilen Alan', 'icon' => 'ozelsigaraicilenalan.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Restoran', 'icon' => 'restorant.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Restoran (Alakart)', 'icon' => 'restorantalakart.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Restoran Büfe', 'icon' => 'restorantbufe.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Sadece Yetişkin', 'icon' => 'sadeceyetiskin.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Ses Geçirmez Odalar', 'icon' => 'sesgecirmezodalar.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Sigara İçilmeyen Odalar', 'icon' => 'sigaraicilmeyendodalar.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Sitede Mini Market', 'icon' => 'sitedeminimarket.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Snack Bar', 'icon' => 'sncakbar.png'],
            [ 'facility_category_id' => 6 , 'name' => 'Chapel / Tapınak', 'icon' => 'tapinak.png'],
            [ 'facility_category_id' => 6 , 'name' => 'Şapel / Tapınak', 'icon' => 'tapinak1.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Vale Park Hizmeti', 'icon' => 'valeparkhizmeti.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Video Gözetimi Olan Girişler', 'icon' => 'videogozetimiolangirisler.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Yağmurlama Sistemi', 'icon' => 'yagmurlamasistemi.png'],
            [ 'facility_category_id' => 6 , 'name' => ' Yangın Dedektörü', 'icon' => 'yangındedektoru.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Aerobik', 'icon' => 'aerobik.png'],
            [ 'facility_category_id' => 7 , 'name' => ' Aile Banyosu', 'icon' => 'ailebanyosu.png'],
            [ 'facility_category_id' => 7 , 'name' => ' Akşam Yemeği', 'icon' => 'aksamyemeği.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Alışveriş Merkezi', 'icon' => 'alısverismerkezi.png'],
            [ 'facility_category_id' => 7 , 'name' => ' Aparetif Meze', 'icon' => 'aparatifmeze.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Tesis Bünyesinde Atm Banka', 'icon' => 'atmtesisbunyesindebanka.png'],
            [ 'facility_category_id' => 7 , 'name' => ' Ayakkabı Parlatıcı', 'icon' => 'ayakkabiparlatici.png'],
            [ 'facility_category_id' => 7 , 'name' => ' Balayı Suiti', 'icon' => 'balayisuiti.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Basketbol', 'icon' => 'basketbol.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Basketbol Sahası', 'icon' => 'basketbolsahasi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Basketbol Sahası Gece', 'icon' => 'basketbolsahasigece.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Bebek Bakım', 'icon' => 'bebekbakimi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Bebek Sandalyesi', 'icon' => 'bebeksandalyesi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Bebek Yatağı', 'icon' => 'bebekyataği.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Beş Çayı', 'icon' => 'bescayi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Bisiklet Kiralama', 'icon' => 'bisikletkiralama.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Bisiklet Mevcut', 'icon' => 'bisikletmevcut.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Bisiklet Servis', 'icon' => 'bisikletservis.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Çamaşırhane', 'icon' => 'camasirhane.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Can Simidi', 'icon' => 'cansimidi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Çevre Dostu', 'icon' => 'cevredostu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Cilt ve Vücut Bakımı', 'icon' => 'ciltvevucutbakimi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Çocuk Animasyonu', 'icon' => 'cocukanimasyonu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Çocuk Büfesi', 'icon' => 'cocukbufesi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Çocuk İçin Uygun', 'icon' => 'cocuklaricinuygun.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Çocuk Restoranı', 'icon' => 'cocukrestorani.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Çocuk Yüzme Havuzu', 'icon' => 'cocukyuzmehavuzu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Denize Sıfır', 'icon' => 'denizesifir1.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Direk Hatlı Telefon', 'icon' => 'direkhatlitelefon.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Doktor', 'icon' => 'doktor.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Döviz Alım Satım', 'icon' => 'dovizalimsatim.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Erken Kahvaltı', 'icon' => 'erkenkahvalti.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Evcil Hayvan', 'icon' => 'evcilhayvan.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Faks Fotokopi', 'icon' => 'faksfotokobi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Fizik Tedavi', 'icon' => 'fiziktedavi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Fotoğrafcı', 'icon' => 'fotografci.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Futbol Sahası', 'icon' => 'futbolsahasi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Gece Akşam Yemeği', 'icon' => 'geceaksamyemegi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Gece Çorbası', 'icon' => 'gececorbasi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Gece Kulübü / DJ', 'icon' => 'gecekulubüdj.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Gelin Suiti', 'icon' => 'gelinsuiti.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Gün Boyu Kapaksız İçecek', 'icon' => 'gunboyukapasizicecek.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Günlük Temizlikçi Servisi', 'icon' => 'gunluktemizlikciservisi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Güzellik Salonu', 'icon' => 'guzelliksalonu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Havaalanı', 'icon' => 'havaalani.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Havaalanı Servisi Ücretli', 'icon' => 'havaalaniservisiucretli.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Havaalanı Servisi Ücretsiz', 'icon' => 'havaalaniservisiucretsiz.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Havuz Şenzongu', 'icon' => 'havuzsenzongu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Hediyelik Eşya Dükkanı', 'icon' => 'hediyelikasyedukkani.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Hemşire', 'icon' => 'hemsire.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Hızlı Check in Check out', 'icon' => 'hızlichankinchakout2.png'],
            [ 'facility_category_id' => 7 , 'name' => 'İçecek Otomatı', 'icon' => 'icecekotomati.png'],
            [ 'facility_category_id' => 7 , 'name' => 'İnternet Cafe', 'icon' => 'internetcafe.png'],
            [ 'facility_category_id' => 7 , 'name' => 'İskele', 'icon' => 'iskele.png'],
            [ 'facility_category_id' => 7 , 'name' => 'İş Merkezi', 'icon' => 'ismerkezi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Jet Ski', 'icon' => 'jet-ski.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kahvaltı', 'icon' => 'kahvalti.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kano', 'icon' => 'kano.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kayak Kartı Bayi', 'icon' => 'kayakkartibayi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kayak Pisti Direk Giriş', 'icon' => 'kayakpistinedirekgiris.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kiralık Araba', 'icon' => 'kiralikaraba.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Konferans Salonu', 'icon' => 'konferanssalonu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Konsiyerj Hizmeti', 'icon' => 'konsiyerjhizmeti.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kredi Kartı Sevisleri', 'icon' => 'kredikartiserfisleri.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kuaför', 'icon' => 'kuafor.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kum Plaj', 'icon' => 'kumplaj.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Kuru Temizleme', 'icon' => 'kurutemizleme.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Langırt', 'icon' => 'langırt.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Makyaj Ajansı', 'icon' => 'makyajajansi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Market', 'icon' => 'market.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Mavi Bayrak', 'icon' => 'mavibayrak.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Mini Bar', 'icon' => 'minibar.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Mini Clup', 'icon' => 'miniclup.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Mutfak', 'icon' => 'mutfak.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Oda Servisi', 'icon' => 'odaservisi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Odaya Kahvaltı Servisi', 'icon' => 'odayakahvaltiservisi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Okçuluk', 'icon' => 'okculuk.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Ortak Tv Salonu', 'icon' => 'ortaktvsalonu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Otelde Kiralık Kayak Ekipmanla', 'icon' => 'oteldekiralıkkayakekipmanlarimevcut.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Otelde Su Sporları', 'icon' => 'oteldesusporlari.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Otel Hizmetleri', 'icon' => 'otelhizmetleri.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Otel Servisi', 'icon' => 'otelservisi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Özel Check in Check out', 'icon' => 'ozelchakinchakout.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Özel Diyet Menüsü (İsteğe Bağl', 'icon' => 'ozeldiyetmenuleriistegebagli.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Paket Öğle Yemeği', 'icon' => 'paketogleyemegi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Pantolon Presi', 'icon' => 'pantolonpresi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Plaj Havlusu', 'icon' => 'plajhavlusu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Plaj Şemsiyesi', 'icon' => 'plajsemsiyesi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Plaj Şenzongu', 'icon' => 'plajsenzongu---Kopya.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Plaj Voleybolu', 'icon' => 'plajvoleybolu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Playstation', 'icon' => 'playstation.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Saç Kurutma Makinesi', 'icon' => 'saçkurutmamakinesi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Sağlık Merkezi', 'icon' => 'saglıkmerkezi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Şezlong', 'icon' => 'sezlong.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Sinema', 'icon' => 'sinema.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Soyunma Kabini', 'icon' => 'soyunmakabini.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Su Kaydırağı', 'icon' => 'sukaydiragi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Su Parkı', 'icon' => 'suparki.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Su Topu', 'icon' => 'sutopu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Tenis Kortu Aydınlatması', 'icon' => 'teniskorduaydinlatmasi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Tenis Kortu Gece', 'icon' => 'teniskortugece.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Teras Cafe', 'icon' => 'terascafe.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Termal Havuz', 'icon' => 'termalhavuz.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Toplantı Salonu', 'icon' => 'toplantisalonu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Transfer Hizmeti', 'icon' => 'transferhizmeti.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Transfer Hizmeti Ücretli', 'icon' => 'transferhizmetiücretli.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Transfer Hizmeti Ücretsiz', 'icon' => 'transferhizmetiücretsiz.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Tur Danışma', 'icon' => 'turdanisma.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Tv', 'icon' => 'tv.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Tv Salonu', 'icon' => 'tvsalonu.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Ücretsiz Banyo Malzemesi', 'icon' => 'ucretsizbanyomalzemesi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Ütü Servisi', 'icon' => 'utuserivisi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Uyandırma Servisi', 'icon' => 'uyandırmaservisi.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Vale Park Hizmeti', 'icon' => 'valeparkhizmeti1.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Wi-fi Kablosuz İnternet', 'icon' => 'vifikablosuzinternet.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Vip Oda Servisleri', 'icon' => 'vipodaservisleri.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Yeşil Anahtar', 'icon' => 'yesilanahtar.png'],
            [ 'facility_category_id' => 7 , 'name' => 'Yiyecek Otomatı', 'icon' => 'yicekotomati.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Açık Aquapark Havuzu Bay', 'icon' => 'acikaquaparkhavuzubay.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Açık Aquapark Havuzu Bayan', 'icon' => 'acikaquaparkhavuzubayan.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Açık Bayan Havuzu', 'icon' => 'acikbayanhavuz.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Açık Bay Havuzu', 'icon' => 'acikbayhavuz.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Açık Yüzme Havuzu', 'icon' => 'acikyuzmehavuzu.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Açık Yüzme Havuzu Sezonluk', 'icon' => 'acikyuzmehavuzusezonluk.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Açık Yüzme Havuzu Yıl Boyu', 'icon' => 'acikyuzmehavuzuyilboyu.png'],
            [ 'facility_category_id' => 4 , 'name' => ' Air Hockey', 'icon' => 'airhockey.png'],
            [ 'facility_category_id' => 4 , 'name' => ' At Binme', 'icon' => 'atbinme.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Balık Tutma', 'icon' => 'baliktutma.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Barbekü', 'icon' => 'barbekü.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bayanlar Çocuk Havuzu', 'icon' => 'bayanlarcocukhavuzu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bayanlar Plajı', 'icon' => 'bayanlarplaji.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bayanlar Spa Merkezi', 'icon' => 'bayanlarsipamerkezi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bayanlar Termal Havuzu', 'icon' => 'bayanlartermalhavuz.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bayanlar Çocuk Havuzu', 'icon' => 'baylarcocukhavuzu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Baylar Çocuk Havuzu', 'icon' => 'baylarcocukhavuzu1.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Baylar Plajı', 'icon' => 'baylarplaji.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Baylar Sıpa Merkezi', 'icon' => 'baylarsipamerkezi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Baylar Termal Havuzu', 'icon' => 'baytermalhavuz.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bilardo', 'icon' => 'bilardo.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bisiklet Binme', 'icon' => 'bisikletbinme.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Boccia', 'icon' => 'boccia.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Bowling', 'icon' => 'bowling.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Buharodasi', 'icon' => 'buharodasi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Çamur Odası', 'icon' => 'camurodasi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Canlı Müzik', 'icon' => 'canlimuzik.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Casino', 'icon' => 'casino.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Çocuk Bahçesi', 'icon' => 'cocukbahcesi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Dalış', 'icon' => 'dalis.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Dart', 'icon' => 'dart.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Eğlence Görevlileri', 'icon' => 'eglencegorevlileri.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Elektronik Bisiklet', 'icon' => 'elektronikbasketbol.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Fitness Merkezi', 'icon' => 'fitnesmerkezi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Galari', 'icon' => 'galari.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Golf Sahası', 'icon' => 'golfsahasi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Hamam Bayanlara Özel', 'icon' => 'hamambayanlaraozel.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Hidro Masaj Küveti', 'icon' => 'hidromasajlikuvet.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Jakuzi', 'icon' => 'jakuzi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kano', 'icon' => 'kano1.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kapalı Aqua Park Havuzu Bay', 'icon' => 'kapaliaquaparkhavuzubay.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kapalı Aqua Park Havuzu Bayan', 'icon' => 'kapaliaquaparkhavuzubayan.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kapalı Bayan Havuzu', 'icon' => 'kapalibayanhavuzu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kapalı Bay Havuzu', 'icon' => 'kapalibayhavuzu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kapalı Yüzme Havuzu Sezonluk', 'icon' => 'kapaliyuzmehavuzusezonluk.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kapalı Yüzme Havuzu Yıl Boyu', 'icon' => 'kapaliyuzmehavuzuyilboyu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Karaoke', 'icon' => 'karaoke.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Karma Açık Havuz', 'icon' => 'karmaacikhavuz.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Karma Aqua Parklı Kapalı Havuz', 'icon' => 'karmaaquaparklikapalihavuz.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Karma Kapalı Havuz', 'icon' => 'karmakapalihavuz.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kayak', 'icon' => 'kayak.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Kayak Okulu', 'icon' => 'kayakokulu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Macera Duşu', 'icon' => 'maceradusu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Masaj', 'icon' => 'masaj.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Masa Tenisi', 'icon' => 'masatenisi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Mini Futbol', 'icon' => 'minifutbol.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Mini Golf', 'icon' => 'minigolf.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Muz', 'icon' => 'muz.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Oyun Odası', 'icon' => 'oyunodasi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Paraşüt', 'icon' => 'parasut.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Ringo', 'icon' => 'ringo.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Rüzgar Sörfü', 'icon' => 'ruzgarsorfu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Sahil Şeridi', 'icon' => 'sahilseridi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Satranç', 'icon' => 'satranc.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Sauna', 'icon' => 'sauna.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Şnorkelle Dalış', 'icon' => 'snorkelledalma.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Sıpa Sağlık Merkezi', 'icon' => 'spasaglikmerkezi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Squash', 'icon' => 'squash.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Tekne Turu', 'icon' => 'tekneturu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Tenis Kortu', 'icon' => 'teniskortu.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Tiyatro', 'icon' => 'tiyatro.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Türk Hamamı', 'icon' => 'turkhamami.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Tuz Odası', 'icon' => 'tuzodasi.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Yelkenli', 'icon' => 'yelkenli.png'],
            [ 'facility_category_id' => 4 , 'name' => 'Yüzme Havuzu', 'icon' => 'yuzmehavuzu.png']
        ];

        foreach ($facilities as $name) {
            Facility::create(
                $name
            );
        }
    }
}
